CREATE OR REPLACE VIEW USER_TRANSACTION_HISTORY AS
SELECT 
    U.USER_NAME,
    U.EMAIL,
    TR.TRANSACTION_ID,
    TR.AMOUNT,
    TR.REFUND_AMOUNT,
    TR.REFUND_STATUS,
    TR.PAYMENT_STATUS,
    TR.TRANSACTION_DATE
FROM 
    USER_TBL U
JOIN 
    BOOKING B ON U.USER_ID = B.USER_USER_ID
JOIN 
    TICKET TK ON TK.BOOKING_BOOKING_ID = B.BOOKING_ID
JOIN 
    TRANSACTION TR ON TR.TICKET_TICKET_ID = TK.TICKET_ID;