CREATE OR REPLACE VIEW TOTAL_SALES_BY_LINE AS
SELECT 
    TL.TRANSIT_LINE_NAME,
    SUM(B.FINAL_TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM 
    BOOKING B
JOIN 
    TRANSIT_LINE TL ON B.TRANSIT_LINE_TRANSIT_LINE_ID = TL.TRANSIT_LINE_ID
GROUP BY 
    TL.TRANSIT_LINE_NAME;
