DELETE FROM DISCOUNT_TYPE;

-- DISCOUNT_TYPE
INSERT INTO DISCOUNT_TYPE VALUES (1, 'Student Discount', 10);
INSERT INTO DISCOUNT_TYPE VALUES (2, 'No Discount', 0);
INSERT INTO DISCOUNT_TYPE VALUES (3, 'Senior Citizen Discount', 15);
INSERT INTO DISCOUNT_TYPE VALUES (4, '3-5Group', 12);
INSERT INTO DISCOUNT_TYPE VALUES (5, '5-8Group', 20);
