-- Drop users safely (optional for rerun safety)
BEGIN EXECUTE IMMEDIATE 'DROP USER app_transit_admin CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER app_customer_user CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER app_txn_manager CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER app_booking_mgr CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER app_subs_mgr CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create Users
CREATE USER app_transit_admin IDENTIFIED BY "AppAdmin#Pass1234";
CREATE USER app_customer_user IDENTIFIED BY "Cust#Pass1234";
CREATE USER app_txn_manager IDENTIFIED BY "Txn#Manager1234";
CREATE USER app_booking_mgr IDENTIFIED BY "Booking#1234Mgr";
CREATE USER app_subs_mgr IDENTIFIED BY "Subs#Manager1234";

-- Grant Connect Role
GRANT CONNECT TO app_transit_admin;
GRANT CONNECT TO app_customer_user;
GRANT CONNECT TO app_txn_manager;
GRANT CONNECT TO app_booking_mgr;
GRANT CONNECT TO app_subs_mgr;


-- ===========================================================
-- ✅ Transit Admin - Full Access to all objects
-- ===========================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.BOOKING TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.TICKET TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.TRANSACTION TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.USER_TBL TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.TRANSIT_LINE TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.SUBSCRIPTION TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.SUBSCRIPTION_TYPE TO app_transit_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.DISCOUNT_TYPE TO app_transit_admin;

-- Views
GRANT SELECT ON APP_TRANSIT_ADMIN.CURRENT_INVENTORY_STATUS TO app_transit_admin;
GRANT SELECT ON APP_TRANSIT_ADMIN.TOTAL_SALES_BY_LINE TO app_transit_admin;
GRANT SELECT ON APP_TRANSIT_ADMIN.WEEKLY_BOOKING_TRENDS TO app_transit_admin;
GRANT SELECT ON APP_TRANSIT_ADMIN.TICKET_USAGE_SUMMARY TO app_transit_admin;
GRANT SELECT ON APP_TRANSIT_ADMIN.USER_TRANSACTION_HISTORY TO app_transit_admin;

-- Procedures and Packages
GRANT EXECUTE ON APP_TRANSIT_ADMIN.PURCHASE_SUBSCRIPTION TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.SUBSCRIPTION_PKG TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.USER_REGISTRATION_PKG TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_USER_DISCOUNT TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.TICKET_BOOKING_PKG TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.VALIDATE_USER TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_ACTIVE_SUBSCRIPTION TO app_transit_admin;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_SUBSCRIPTION_TYPE_ID TO app_transit_admin;

-- ===========================================================
-- ✅ Customer User - Read-Only + Booking + Subscription
-- ===========================================================
GRANT SELECT ON APP_TRANSIT_ADMIN.TRANSIT_LINE TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.BOOKING TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.TICKET TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.SUBSCRIPTION TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.CURRENT_INVENTORY_STATUS TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.WEEKLY_BOOKING_TRENDS TO app_customer_user;
GRANT SELECT ON APP_TRANSIT_ADMIN.TICKET_USAGE_SUMMARY TO app_customer_user;

GRANT EXECUTE ON APP_TRANSIT_ADMIN.PURCHASE_SUBSCRIPTION TO app_customer_user;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.TICKET_BOOKING_PKG TO app_customer_user;

-- ===========================================================
-- ✅ Transaction Manager
-- ===========================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.TRANSACTION TO app_txn_manager;
GRANT SELECT ON APP_TRANSIT_ADMIN.TICKET TO app_txn_manager;
GRANT SELECT ON APP_TRANSIT_ADMIN.BOOKING TO app_txn_manager;
GRANT SELECT ON APP_TRANSIT_ADMIN.USER_TBL TO app_txn_manager;
GRANT SELECT ON APP_TRANSIT_ADMIN.USER_TRANSACTION_HISTORY TO app_txn_manager;

GRANT EXECUTE ON APP_TRANSIT_ADMIN.TICKET_BOOKING_PKG TO app_txn_manager;

-- ===========================================================
-- ✅ Booking Manager
-- ===========================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.BOOKING TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.TRANSIT_LINE TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.DISCOUNT_TYPE TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.USER_TBL TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.CURRENT_INVENTORY_STATUS TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.TOTAL_SALES_BY_LINE TO app_booking_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.WEEKLY_BOOKING_TRENDS TO app_booking_mgr;

GRANT EXECUTE ON APP_TRANSIT_ADMIN.TICKET_BOOKING_PKG TO app_booking_mgr;

-- ===========================================================
-- ✅ Subscription Manager
-- ===========================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON APP_TRANSIT_ADMIN.SUBSCRIPTION TO app_subs_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.SUBSCRIPTION_TYPE TO app_subs_mgr;
GRANT SELECT ON APP_TRANSIT_ADMIN.USER_TBL TO app_subs_mgr;

GRANT EXECUTE ON APP_TRANSIT_ADMIN.USER_REGISTRATION_PKG TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_USER_DISCOUNT TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.VALIDATE_USER TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_SUBSCRIPTION_TYPE_ID TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.GET_ACTIVE_SUBSCRIPTION TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.SUBSCRIPTION_PKG TO app_subs_mgr;
GRANT EXECUTE ON APP_TRANSIT_ADMIN.PURCHASE_SUBSCRIPTION TO app_subs_mgr;
