CREATE TABLE USER_TBL (
    USER_ID                         INTEGER NOT NULL,
    USER_NAME                       VARCHAR2(100) NOT NULL,
    PASSWORD                        VARCHAR2(100) NOT NULL,
    EMAIL                           VARCHAR2(100) NOT NULL,
    USER_TYPE                       VARCHAR2(100),
    CREATED_AT                      DATE NOT NULL,
    DISCOUNT_TYPE_DISCOUNT_TYPE_ID INTEGER NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_EMAIL_UN UNIQUE (EMAIL),
    CONSTRAINT USER_DISCOUNT_TYPE_FK FOREIGN KEY (DISCOUNT_TYPE_DISCOUNT_TYPE_ID) REFERENCES DISCOUNT_TYPE(DISCOUNT_TYPE_ID)
);
