BEGIN EXECUTE IMMEDIATE 'DROP TABLE TICKET CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/



CREATE TABLE TICKET (
    TICKET_ID                     INTEGER NOT NULL,
    PURCHASE_DATE                 DATE NOT NULL,
    PURCHASE_TIME                 TIMESTAMP NOT NULL,
    AMOUNT                        NUMBER(5,2) NOT NULL,
    TICKET_STATUS                 VARCHAR2(100) NOT NULL,
    TRANSIT_LINE_TRANSIT_LINE_ID INTEGER NOT NULL,
    BOOKING_BOOKING_ID           INTEGER NOT NULL,
    CONSTRAINT TICKET_PK PRIMARY KEY (TICKET_ID),
    CONSTRAINT TICKET_TRANSIT_LINE_FK FOREIGN KEY (TRANSIT_LINE_TRANSIT_LINE_ID) REFERENCES TRANSIT_LINE(TRANSIT_LINE_ID),
    CONSTRAINT TICKET_BOOKING_FK FOREIGN KEY (BOOKING_BOOKING_ID) REFERENCES BOOKING(BOOKING_ID)
);