BEGIN EXECUTE IMMEDIATE 'DROP TABLE BOOKING CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE BOOKING (
    BOOKING_ID                      INTEGER NOT NULL,
    BOOKING_DATE                    DATE NOT NULL,
    NUM_PASSENGERS                  INTEGER NOT NULL,
    DISCOUNT_APPLIED                CHAR(1),
    TOTAL_AMOUNT                    NUMBER(5,2) NOT NULL,
    FINAL_TOTAL_AMOUNT              NUMBER(5,2),
    USER_USER_ID                    INTEGER NOT NULL,
    TRANSIT_LINE_TRANSIT_LINE_ID    INTEGER NOT NULL,
    DISCOUNT_TYPE_DISCOUNT_TYPE_ID INTEGER NOT NULL,
    CONSTRAINT BOOKING_PK PRIMARY KEY (BOOKING_ID),
    CONSTRAINT BOOKING_USER_FK FOREIGN KEY (USER_USER_ID) REFERENCES USER_TBL(USER_ID),
    CONSTRAINT BOOKING_TRANSIT_LINE_FK FOREIGN KEY (TRANSIT_LINE_TRANSIT_LINE_ID) REFERENCES TRANSIT_LINE(TRANSIT_LINE_ID),
    CONSTRAINT BOOKING_DISCOUNT_TYPE_FK FOREIGN KEY (DISCOUNT_TYPE_DISCOUNT_TYPE_ID) REFERENCES DISCOUNT_TYPE(DISCOUNT_TYPE_ID)
);