BEGIN EXECUTE IMMEDIATE 'DROP TABLE DISCOUNT_TYPE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DISCOUNT_TYPE (
    DISCOUNT_TYPE_ID    INTEGER NOT NULL,
    DISCOUNT_NAME       VARCHAR2(100),
    DISCOUNT_PERCENTAGE INTEGER NOT NULL,
    CONSTRAINT DISCOUNT_TYPE_PK PRIMARY KEY (DISCOUNT_TYPE_ID)
);