BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUBSCRIPTION_TYPE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE SUBSCRIPTION_TYPE (
    SUBSCRIPTION_TYPE_ID INTEGER NOT NULL,
    SUBSCRIPTION_NAME    VARCHAR2(100),
    AMOUNT               NUMBER(5,2) NOT NULL,
    CONSTRAINT SUBSCRIPTION_TYPE_PK PRIMARY KEY (SUBSCRIPTION_TYPE_ID)
);
