BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRANSACTION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE TRANSACTION (
    TRANSACTION_ID     INTEGER NOT NULL,
    AMOUNT             NUMBER(5,2) NOT NULL,
    REFUND_AMOUNT      NUMBER(5,2),
    REFUND_STATUS      VARCHAR2(100),
    PAYMENT_STATUS     VARCHAR2(100) NOT NULL,
    TRANSACTION_DATE   DATE NOT NULL,
    TICKET_TICKET_ID   INTEGER NOT NULL,
    CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT TRANSACTION_TICKET_FK FOREIGN KEY (TICKET_TICKET_ID) REFERENCES TICKET(TICKET_ID)
);
